export const GET_SPOTIFY_PLAYLISTS_REQUEST = "GET_SPOTIFY_PLAYLISTS_REQUEST";
export const GET_FIRESTORE_PLAYLISTS_REQUEST =
  "GET_FIRESTORE_PLAYLISTS_REQUEST";
export const GET_FIRESTORE_PLAYLISTS_TRACKS_REQUEST =
  "GET_FIRESTORE_PLAYLISTS_TRACKS_REQUEST";
export const GET_SPOTIFY_PLAYLISTS_TRACKS_REQUEST =
  "GET_SPOTIFY_PLAYLISTS_TRACKS_REQUEST";
export const SELECT_SPOTIFY_PLAYLIST_REQUEST =
  "SELECT_SPOTIFY_PLAYLIST_REQUEST";
export const SELECT_FIRESTORE_PLAYLIST_REQUEST =
  "SELECT_FIRESTORE_PLAYLIST_REQUEST";
export const CHECK_SYNC_NEEDED_REQUEST = "CHECK_SYNC_NEEDED_REQUEST";
