export const USER_BY_EMAIL_REQUEST = "USER_BY_EMAIL_REQUEST";
export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_GET_SPOTIFY_USER_REQUEST = "USER_GET_SPOTIFY_USER_REQUEST";
